name: Update Data

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  update-data:
    name: Update Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Fetch JustWatch
        run: npm run justwatch
      - name: Fetch TMDB
        run: npm run tmdb
        env: 
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          git diff-index --quiet HEAD || git commit -m  "Updated data" && git push